# Generated by Django 4.1 on 2022-12-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_hobby_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hobby_tb',
            new_name='hobbyname_tb',
        ),
    ]
