# Generated by Django 4.1 on 2022-12-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0007_seasoncountry_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasoncountry_tb',
            old_name='factorid',
            new_name='season_factorid',
        ),
    ]
