# Generated by Django 4.1 on 2022-12-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0008_rename_factorid_seasoncountry_tb_season_factorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasoncountry_tb',
            name='months',
            field=models.IntegerField(max_length=20),
        ),
    ]
