# Generated by Django 4.1 on 2022-12-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0003_rename_hobby_tb_hobbyname_tb'),
        ('user', '0003_user_register_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobby_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobbyname_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register_tb')),
            ],
        ),
    ]
