# Generated by Django 4.1 on 2022-12-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_message_tb_filter_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('messageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.message_tb')),
                ('receiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register_tb')),
            ],
        ),
    ]
