# Generated by Django 4.1 on 2022-12-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_blacklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blacklist',
            new_name='blacklist_tb',
        ),
    ]
