# Generated by Django 4.1 on 2022-12-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0011_alter_agefactor_tb_maximum_age_and_more'),
        ('user', '0010_rename_blacklist_blacklist_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_hobbyfactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobbyfactor_tb')),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobbyname_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register_tb')),
            ],
        ),
    ]
