# Generated by Django 4.1 on 2022-12-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0011_alter_agefactor_tb_maximum_age_and_more'),
        ('user', '0011_customer_hobbyfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.agefactor_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register_tb')),
            ],
        ),
    ]
